services:
  web:
    image: ${IMAGE_TAG} # Wird von der Pipeline automatisch gesetzt
    restart: unless-stopped
    environment:
      - PORT=${PORT:-3000}
      - MESSAGE_SUFFIX=${MESSAGE_SUFFIX}
    labels:
      caddy: "http://${FQDN}"
      caddy.reverse_proxy: "{{upstreams ${PORT:-3000}}}"
    networks:
      - default
      - caddy_net

networks:
  caddy_net:
    external: true